[package]
name = "gungnir-core"
version = "0.1.0"
edition = "2024"

[features]
pext = ["gungnir-types/pext"]

[dependencies]
gungnir-types = { path = "../gungnir-types" }

[build-dependencies]
gungnir-types = { path = "../gungnir-types" }